# Generated by Django 5.0.1 on 2024-01-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predicted')),
                ('model', models.CharField(choices=[('1', 'Model 1 - InceptionV3'), ('2', 'Model 2 -  ResNet50V1 Dropout'), ('3', 'Model 3 - ResNet50V1 Sequential Model'), ('4', 'Model 4 - ResNet50V2 Dropout'), ('5', 'Model 5 - ResNet50V2 Sequential Model')], max_length=100)),
                ('predicted_value', models.CharField(max_length=10)),
                ('likelihood_indoor', models.FloatField()),
                ('likelihood_outdoor', models.FloatField()),
            ],
        ),
    ]
